### ISSUE TITLE
Prepare Power Supplies

### ISSUE THREAD

**Issue by vphill** [unt-carpentries/2018-03-14-unt-swc#2]
The power supplies we purchased for SWC need two things done to them ideally before this event. 

- [x]  Add velcro cable wraps to each powerstrip so they hold together better.
- [x] Write "UNT Carpentries" on the side/back of the power strip so that we don't forget them

**Comment by ldko** [comment]
Gio added velcro. Lauren Wrote "UNT CARPENTRIES" on the back of the strips.
