### ISSUE TITLE
Adding info to the Website

### ISSUE THREAD

**Issue by vphill** [unt-carpentries/2018-03-14-unt-swc#3]
- [x] Eventbrite Numbers (from @ldko)
- [x] Update syllabus 
- [x] Adjust Schedule - Add hard end times for breaks (10 min) Shift lunch half an hour later to allow more time in the morning.
- [x] Update pre- and post- workshop links (this actually is automatically populated)

## Instructors
Jason - Python
Mark - Python
Kristy - Unix
Gio - Git

## Helpers
Pamela
Bill
Tom Miles (maybe)

**Comment by somexpert** [comment]
I'm gonna go ahead and add in the information that we already have available to us.

**Comment by somexpert** [comment]
quick channel notification test

**Comment by somexpert** [comment]
let's try this again

**Comment by somexpert** [comment]
I _think_ I got everything, but I'd welcome anyone to double-check.

**Comment by ldko** [comment]
Looks good to me

**Comment by ldko** [comment]
Completed!
