### ISSUE TITLE
Setup Eventbrite / Etherpad

### ISSUE THREAD

**Issue by vphill** [unt-carpentries/2018-03-14-unt-swc#4]
- [x] Setup Eventbrite for the event.  Put 8:30 start time on eventbrite and then we will actually kick off at 9:00 on the SWC instructions.
- [x] Setup Etherpad

**Comment by ldko** [comment]
Links are:
https://www.eventbrite.com/e/unt-software-carpentry-march-14-15-2018-tickets-43321670282
http://pad.software-carpentry.org/2018-03-14-UNT
