### ISSUE TITLE
Create map / local eating places

### ISSUE THREAD

**Issue by vphill** [unt-carpentries/2018-03-14-unt-swc#5]
Find out what good fast places to go and eat and maybe a little map.

**Comment by somexpert** [comment]
I'll start with some aerial reconnaissance

**Comment by somexpert** [comment]
So, the nearest quick meal looks like
- Subway

A little farther to the NW we have:
- Palio's

Then, either in or around the Stonebriar mall we have:

- Sonic
- Panda Express
- Sbarro
- Chick-fil-A
- Jason's Deli
- Starbucks
- Fuzzy's
- In-N-Out Burger
- Red Hot Chili Pepper
- Pizza Hut Express
- Buffalo Wild Wings
- Genghis Grill
- Chipotle
- Corner Bakery

**Comment by somexpert** [comment]
Here is a short link to the google maps search that gives some quick results (not all of them, there are a _ton_ of nearby food places). https://goo.gl/maps/nd6xyxG9cYT2

**Comment by somexpert** [comment]
Initial attempt... 
[Quick Lunch Options.pdf](https://github.com/unt-carpentries/2018-03-14-unt-swc/files/1768552/Quick.Lunch.Options.pdf)

**Comment by somexpert** [comment]
Better attempt.....
[food_places.pdf](https://github.com/unt-carpentries/2018-03-14-unt-swc/files/1772822/document.1.pdf)

**Comment by somexpert** [comment]
Calling this done.
