### ISSUE TITLE
Create Welcome Handout

### ISSUE THREAD

**Issue by vphill** [unt-carpentries/2018-03-14-unt-swc#7]
Create a welcome handout that has the following pieces of information. 

* Short link to the Etherpad
* Checklist for the following:
** Pre-Workshop Survey
** Install Anaconda and a test command
** Install Git and a test command
* Brief sticky note instructions

**Comment by somexpert** [comment]
@pandrews completed this one and I'm about to print a bunch of them out, so closing this.

**Comment by somexpert** [comment]
In case we want this for future reference, this is what the printed version ended up looking like
[WelcomeHandout.pdf](https://github.com/unt-carpentries/2018-03-14-unt-swc/files/1798014/WelcomeHandout.pdf)
